# Generated by Django 5.2.7 on 2025-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('is_phishing', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
