# Generated by Django 5.2.7 on 2025-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
